-- vim.o.cedit = "<C-f>"
-- vim.o.clipboard = ""
-- vim.o.cmdheight = 1
-- vim.o.cmdwinheight = 7
-- vim.o.colorcolumn = ""
-- vim.o.completeitemalign = "abbr,kind,menu"
vim.o.completeopt = "menu,menuone,popup,fuzzy"
-- vim.o.conceallevel = 0
vim.o.confirm = true
-- vim.o.cursorline = false
vim.o.expandtab = true
-- vim.o.foldcolumn = "0"
vim.o.foldenable = false
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
-- vim.o.foldlevel = 0
-- vim.o.foldlevelstart = -1
vim.o.foldmethod = "expr"
-- vim.o.guicursor = "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,t:block-blinkon500-blinkoff500-TermCursor"
vim.o.helpheight = 0
vim.o.ignorecase = true
vim.o.inccommand = "split"
-- vim.o.list = false
-- vim.o.listchar = "tab:> ,trail:-,nbsp:+"
-- vim.o.matchpairs = "(:),{:},[:]"
-- vim.o.messagesopt = "hit-enter,history:500"
vim.o.mouse = "nv"
-- vim.o.number = true
-- vim.o.numberwidth = 4
vim.o.pumheight = 10
vim.o.relativenumber = true
vim.o.ruler = false
vim.o.scrolloff = 5
vim.o.shiftwidth = 2
-- TODO
vim.o.shortmess = "sWAIcCqFS"
vim.o.showcmd = false
-- vim.o.showcmdloc = "last"
vim.o.showmode = false
-- vim.o.showtabline = 1
vim.o.signcolumn = "yes:1"
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.smoothscroll = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.swapfile = false
vim.o.tabstop = 2
vim.o.termguicolors = true
vim.o.undofile = true
vim.o.winborder = "rounded"
vim.o.wrap = false
